FROM centos:7.6.1810

RUN yum install -y java-1.8.0-openjdk.x86_64

ADD install /install
ENV AEMNODE author
ENV AEMPORT 4502

WORKDIR /install

RUN cp -f "$AEMNODE"-tar.quickstart /install/crx-quickstart/bin/quickstart
RUN chmod +x /install/crx-quickstart/bin/quickstart

EXPOSE $AEMPORT
CMD crx-quickstart/bin/quickstart





