FROM hub.myregistry.io/aem/aem-base:640-author-tarmk-1.0.0

ENV AEMNODE publish
ENV AEMPORT 4503

WORKDIR /install

RUN cp -f "$AEMNODE"-tar.quickstart /install/crx-quickstart/bin/quickstart
RUN chmod +x /install/crx-quickstart/bin/quickstart

EXPOSE $AEMPORT
CMD crx-quickstart/bin/quickstart

