FROM hub.myregistry.io/aem/aem-base:640-author-tarmk-1.0.0

ENV AEMNODE author
ENV AEMPORT 4502

WORKDIR /install

RUN mkdir -p /install/crx-quickstart/install; \
    cp -f org.apache.jackrabbit.oak.plugins.blob.datastore.FileDataStore.cfg /install/crx-quickstart/install/; \
    cp -f org.apache.jackrabbit.oak.plugins.document.DocumentNodeStoreService.cfg /install/crx-quickstart/install/;

RUN mkdir -p /install/crx-quickstart/custombin; \
    cp -f "$AEMNODE"-mongo.quickstart /install/crx-quickstart/custombin/quickstart; \
    chmod +x /install/crx-quickstart/custombin/quickstart;

EXPOSE $AEMPORT
CMD crx-quickstart/custombin/quickstart

