version: "2"
services:
  mongorep01:
    image: hub.myregistry.io/aem/mongo:4.0.7
    container_name: mongorep01
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongopassword
    command: mongod --replSet "aemrs0" --bind_ip mongorep01 --keyFile /data/db/keyfile
    volumes:
      - /opt/aemdata/mongodata/mongorep01:/data/db
    ports:
      - 27101:27017
  mongorep02:
    image: hub.myregistry.io/aem/mongo:4.0.7
    container_name: mongorep02
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongopassword
    command: mongod --replSet "aemrs0" --bind_ip mongorep02 --keyFile /data/db/keyfile
    volumes:
      - /opt/aemdata/mongodata/mongorep02:/data/db
    ports:
      - 27102:27017
